package bfst20.mapdrawer.map;

import javafx.scene.paint.Color;
/*
public enum PathColorBlind {
    UNKNOWN(Color.RED),
    BUILDING(Color.SADDLEBROWN),
    HIGHWAY(Color.YELLOW),
    COASTLINE(Color.GREY),
    WATER(Color.LIGHTBLUE),
    BEACH(Color.YELLOW),
    FOREST(Color.FORESTGREEN),
    COMMERCIAL(Color.LIGHTPINK),
    CONSTRUCTION(Color.LIGHTGREY),
    ALLOTMENTS(Color.LIGHTGREEN),
    FARMLAND(Color.LIGHTGOLDENRODYELLOW),
    MEADOW(Color.LIGHTGREEN),
    ORCHARD(Color.GREEN),
    BASIN(Color.LIGHTBLUE),
    BROWNFIELD(Color.DARKKHAKI),
    CEMETERY(Color.LIGHTGREEN),
    GRASS(Color.LAWNGREEN),
    RESERVOIR(Color.LIGHTBLUE),
    VILLAGE_GREEN(Color.LIGHTGREEN),
    PARK(Color.LIGHTGREEN),
    DANGER_AREA(Color.TOMATO),
    QUARRY(Color.LIGHTGREY),
    WOOD(Color.FORESTGREEN),
    HEATH(Color.WHEAT),
    GRASSLAND(Color.LAWNGREEN),
    SCRUB(Color.DARKOLIVEGREEN),
    SEARCH(Color.RED),
    NONE(Color.BLACK);
}


 */